# Generated by Django 4.2.7 on 2026-07-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['user', '-created_at'], name='reports_rep_user_id_dcf374_idx'),
        ),
    ]
