"""
Professional PDF Report Generator using ReportLab.
Generates multi-section reports with tables, metrics, and business recommendations.
"""
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak, KeepTogether
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime

# ── Color Palette ──────────────────────────────────────────
PRIMARY   = colors.HexColor('#3B82F6')   # Blue
SECONDARY = colors.HexColor('#8B5CF6')   # Purple
ACCENT    = colors.HexColor('#10B981')   # Green
DANGER    = colors.HexColor('#EF4444')   # Red
WARNING   = colors.HexColor('#F59E0B')   # Amber
BG_LIGHT  = colors.HexColor('#F8FAFC')   # Light gray
TEXT_DARK = colors.HexColor('#1E293B')   # Dark
TEXT_MUTED= colors.HexColor('#64748B')   # Muted gray


def generate_pdf_report(prediction, company_name: str, output_path: str) -> str:
    """
    Generate a professional multi-page PDF sales report.
    Args:
        prediction: Django Prediction model instance
        company_name: Name printed in the report header
        output_path: Full filesystem path to write the PDF
    Returns:
        output_path (for chaining)
    """
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    story  = []

    # ── Custom styles ──────────────────────────────────────
    title_style = ParagraphStyle(
        'CustomTitle', parent=styles['Title'],
        fontSize=22, textColor=PRIMARY, spaceAfter=4, alignment=TA_CENTER
    )
    subtitle_style = ParagraphStyle(
        'Subtitle', parent=styles['Normal'],
        fontSize=11, textColor=SECONDARY, spaceAfter=10, alignment=TA_CENTER
    )
    h1_style = ParagraphStyle(
        'H1', parent=styles['Heading1'],
        fontSize=15, textColor=PRIMARY, spaceBefore=14, spaceAfter=6
    )
    h2_style = ParagraphStyle(
        'H2', parent=styles['Heading2'],
        fontSize=12, textColor=SECONDARY, spaceBefore=10, spaceAfter=5
    )
    body_style = ParagraphStyle(
        'Body', parent=styles['Normal'],
        fontSize=10, textColor=TEXT_DARK, spaceAfter=5, leading=14
    )
    footer_style = ParagraphStyle(
        'Footer', parent=styles['Normal'],
        fontSize=8, textColor=TEXT_MUTED, alignment=TA_CENTER
    )
    footer_bold_style = ParagraphStyle(
        'FooterBold', parent=styles['Normal'],
        fontSize=8, textColor=DANGER, alignment=TA_CENTER
    )

    # ── HEADER ─────────────────────────────────────────────
    story.append(Paragraph(company_name, title_style))
    story.append(Paragraph('AI-Powered Sales &amp; Revenue Forecasting Report', subtitle_style))
    story.append(HRFlowable(width='100%', thickness=2, color=PRIMARY, spaceAfter=10))

    # Metadata table
    meta_rows = [
        ['Report Title',  prediction.name],
        ['Generated On',  datetime.now().strftime('%B %d, %Y at %I:%M %p')],
        ['ML Model Used', prediction.model_type.upper()],
        ['Generated By',  str(prediction.user)],
    ]
    if prediction.dataset:
        meta_rows.insert(1, ['Dataset', prediction.dataset.name])

    meta_table = Table(meta_rows, colWidths=[4 * cm, 12.5 * cm])
    meta_table.setStyle(TableStyle([
        ('FONTSIZE',   (0, 0), (-1, -1), 9),
        ('FONTNAME',   (0, 0), (0, -1),  'Helvetica-Bold'),
        ('TEXTCOLOR',  (0, 0), (0, -1),  TEXT_MUTED),
        ('TEXTCOLOR',  (1, 0), (1, -1),  TEXT_DARK),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 0.25 * inch))

    # ── MODEL PERFORMANCE ──────────────────────────────────
    story.append(Paragraph('Model Performance Metrics', h1_style))
    story.append(HRFlowable(width='100%', thickness=1, color=colors.lightgrey, spaceAfter=6))

    def fmt_inr(val):
        return f'Rs.{val:,.2f}' if val is not None else 'N/A'

    metrics_data = [
        ['Metric', 'Value', 'Benchmark'],
        ['MAE (Mean Absolute Error)',      fmt_inr(prediction.mae),  'Lower is better'],
        ['RMSE (Root Mean Square Error)',  fmt_inr(prediction.rmse), 'Lower is better'],
        ['R2 Score',                       f'{prediction.r2_score:.4f}' if prediction.r2_score else 'N/A', '>0.80 is excellent'],
        ['MAPE (%)',                       f'{prediction.mape:.2f}%'  if prediction.mape else 'N/A', 'Lower is better'],
    ]

    mt = Table(metrics_data, colWidths=[6 * cm, 5 * cm, 5.5 * cm])
    mt.setStyle(TableStyle([
        ('BACKGROUND',   (0, 0), (-1, 0), PRIMARY),
        ('TEXTCOLOR',    (0, 0), (-1, 0), colors.white),
        ('FONTNAME',     (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE',     (0, 0), (-1, -1), 9),
        ('ALIGN',        (0, 0), (-1, -1), 'CENTER'),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [BG_LIGHT, colors.white]),
        ('GRID',         (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ('TOPPADDING',   (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING',(0, 0), (-1, -1), 5),
    ]))
    story.append(mt)
    story.append(Spacer(1, 0.25 * inch))

    # ── REVENUE SUMMARY ────────────────────────────────────
    result = prediction.result_json or {}
    if result:
        story.append(Paragraph('Revenue Analysis Summary', h1_style))
        story.append(HRFlowable(width='100%', thickness=1, color=colors.lightgrey, spaceAfter=6))

        actual_rev    = result.get('total_actual_revenue', 0)
        predicted_rev = result.get('total_predicted_revenue', 0)
        accuracy_pct  = (1 - abs(actual_rev - predicted_rev) / max(actual_rev, 1)) * 100

        rev_data = [
            ['Metric', 'Amount'],
            ['Total Actual Revenue',    fmt_inr(actual_rev)],
            ['Total Predicted Revenue', fmt_inr(predicted_rev)],
            ['Prediction Accuracy',     f'{accuracy_pct:.1f}%'],
            ['Total Sales Records',     str(result.get('total_actual_sales', 'N/A'))],
            ['Forecast Period',         f"{result.get('forecast_months', 6)} Months"],
        ]

        rt = Table(rev_data, colWidths=[8 * cm, 8.5 * cm])
        rt.setStyle(TableStyle([
            ('BACKGROUND',   (0, 0), (-1, 0), SECONDARY),
            ('TEXTCOLOR',    (0, 0), (-1, 0), colors.white),
            ('FONTNAME',     (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTNAME',     (0, 1), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE',     (0, 0), (-1, -1), 9),
            ('ALIGN',        (1, 0), (1, -1), 'RIGHT'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [BG_LIGHT, colors.white]),
            ('GRID',         (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ('TOPPADDING',   (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING',(0, 0), (-1, -1), 6),
        ]))
        story.append(rt)
        story.append(Spacer(1, 0.25 * inch))

        # ── TOP PRODUCTS ───────────────────────────────────
        products = result.get('product_summary', [])
        if products:
            story.append(Paragraph('Top Products by Revenue', h1_style))
            story.append(HRFlowable(width='100%', thickness=1, color=colors.lightgrey, spaceAfter=6))

            prod_data = [['Rank', 'Product', 'Revenue', 'Quantity']]
            for i, p in enumerate(products[:8], 1):
                prod_data.append([
                    str(i),
                    p.get('product', 'N/A'),
                    fmt_inr(p.get('revenue')),
                    str(p.get('quantity', 'N/A')),
                ])

            pt = Table(prod_data, colWidths=[1.5 * cm, 8.5 * cm, 4 * cm, 2.5 * cm])
            pt.setStyle(TableStyle([
                ('BACKGROUND',   (0, 0), (-1, 0), ACCENT),
                ('TEXTCOLOR',    (0, 0), (-1, 0), colors.white),
                ('FONTNAME',     (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE',     (0, 0), (-1, -1), 9),
                ('ALIGN',        (0, 0), (0, -1), 'CENTER'),
                ('ALIGN',        (2, 0), (2, -1), 'RIGHT'),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [BG_LIGHT, colors.white]),
                ('GRID',         (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ('TOPPADDING',   (0, 0), (-1, -1), 5),
                ('BOTTOMPADDING',(0, 0), (-1, -1), 5),
            ]))
            story.append(pt)
            story.append(Spacer(1, 0.25 * inch))

        # ── MONTHLY FORECAST ───────────────────────────────
        forecast = result.get('forecast', {})
        future   = forecast.get('future', [])
        if future:
            story.append(Paragraph('Monthly Revenue Forecast', h1_style))
            story.append(HRFlowable(width='100%', thickness=1, color=colors.lightgrey, spaceAfter=6))

            fc_data = [['Month', 'Predicted Revenue', 'Predicted Sales']]
            for f in future:
                fc_data.append([
                    f.get('month', 'N/A'),
                    fmt_inr(f.get('predicted_revenue')),
                    str(f.get('predicted_sales', 'N/A')),
                ])

            fct = Table(fc_data, colWidths=[5 * cm, 6 * cm, 5.5 * cm])
            fct.setStyle(TableStyle([
                ('BACKGROUND',   (0, 0), (-1, 0), WARNING),
                ('TEXTCOLOR',    (0, 0), (-1, 0), colors.white),
                ('FONTNAME',     (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE',     (0, 0), (-1, -1), 9),
                ('ALIGN',        (1, 0), (-1, -1), 'RIGHT'),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [BG_LIGHT, colors.white]),
                ('GRID',         (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ('TOPPADDING',   (0, 0), (-1, -1), 5),
                ('BOTTOMPADDING',(0, 0), (-1, -1), 5),
            ]))
            story.append(fct)
            story.append(PageBreak())

    # ── AI RECOMMENDATIONS ─────────────────────────────────
    recommendations = prediction.recommendations or []
    if recommendations:
        story.append(Paragraph('AI Business Recommendations', h1_style))
        story.append(HRFlowable(width='100%', thickness=1, color=colors.lightgrey, spaceAfter=8))

        for i, rec in enumerate(recommendations, 1):
            priority = rec.get('priority', 'medium').upper()
            p_color  = PRIMARY if priority == 'HIGH' else (WARNING if priority == 'MEDIUM' else ACCENT)

            rec_rows = [
                [f"{i}. {rec.get('title', 'Recommendation')}"],
                [rec.get('description', '')],
                [f"Priority: {priority}   |   Type: {rec.get('type', 'general').upper()}   |   Action: {rec.get('action', '')}"],
            ]
            rec_t = Table(rec_rows, colWidths=[16.5 * cm])
            rec_t.setStyle(TableStyle([
                ('BACKGROUND',   (0, 0), (0, 0), p_color),
                ('TEXTCOLOR',    (0, 0), (0, 0), colors.white),
                ('FONTNAME',     (0, 0), (0, 0), 'Helvetica-Bold'),
                ('FONTSIZE',     (0, 0), (0, 0), 10),
                ('BACKGROUND',   (0, 1), (0, 1), BG_LIGHT),
                ('FONTSIZE',     (0, 1), (0, 1), 9),
                ('BACKGROUND',   (0, 2), (0, 2), colors.white),
                ('FONTSIZE',     (0, 2), (0, 2), 8),
                ('TEXTCOLOR',    (0, 2), (0, 2), TEXT_MUTED),
                ('TOPPADDING',   (0, 0), (-1, -1), 6),
                ('BOTTOMPADDING',(0, 0), (-1, -1), 6),
                ('LEFTPADDING',  (0, 0), (-1, -1), 10),
                ('GRID',         (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ]))
            story.append(rec_t)
            story.append(Spacer(1, 0.08 * inch))

    # ── FOOTER ─────────────────────────────────────────────
    story.append(Spacer(1, 0.25 * inch))
    story.append(HRFlowable(width='100%', thickness=1, color=colors.lightgrey))
    story.append(Spacer(1, 0.08 * inch))
    story.append(Paragraph(
        f'Generated by AI-Powered Sales Forecasting Platform | {company_name} | {datetime.now().year}',
        footer_style
    ))
    story.append(Paragraph('CONFIDENTIAL – For Internal Use Only', footer_bold_style))

    doc.build(story)
    return output_path
