# Generated by Django 4.2.7 on 2026-07-24 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predictions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Scenario', max_length=200)),
                ('marketing_budget', models.FloatField(default=100000)),
                ('product_price', models.FloatField(default=1000)),
                ('discount_percent', models.FloatField(default=10)),
                ('expected_demand', models.FloatField(default=500)),
                ('base_revenue', models.FloatField(blank=True, null=True)),
                ('simulated_revenue', models.FloatField(blank=True, null=True)),
                ('revenue_difference', models.FloatField(blank=True, null=True)),
                ('revenue_change_percent', models.FloatField(blank=True, null=True)),
                ('simulation_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='predictions.prediction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
