# Generated by Django 4.2.7 on 2026-07-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scenariosimulation',
            index=models.Index(fields=['user', '-created_at'], name='scenarios_s_user_id_e1217b_idx'),
        ),
    ]
